export const COMPANY_DETAILS = {
  name: "K2 Pest Control",
  tagline: "Licensed, Guaranteed & Eco-Conscious Exterminators for Saskatoon & Area",
  slogan: "Licensed, Guaranteed & Eco-Conscious Exterminators for Saskatoon & Area",
  logoUrl: "/assets/logo.png",
  shortName: "K2 Pest Control",
  phone: "(306) 407-0007",
  phoneRaw: "3064070007",
  email: "info@k2pc.ca",
  licenseNumber: "SK-719402",
  provincialBody: "Saskatchewan Ministry of Environment",
  googleMapsUrl: "https://share.google/IMFOd1tJPGI6JL4OJ",
  googleMapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9792.44774900138!2d-106.68346491284177!3d52.15047400000001!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4c3c99168292ddd9%3A0xf3d49338a57961d!2sK2%20Pest%20Control%20Ltd!5e0!3m2!1sen!2sus!4v1786799545276!5m2!1sen!2sus",
  address: {
    street: "1200 Central Ave, Suite 400",
    city: "Saskatoon",
    province: "SK",
    postalCode: "S7N 2H2",
    country: "Canada",
  },
  hours: [
    { days: "Monday - Friday", times: "7:00 AM - 9:00 PM" },
    { days: "Saturday - Sunday", times: "8:00 AM - 6:00 PM" },
    { days: "Emergency Response", times: "24/7 Rapid Dispatch" },
  ],
  stats: {
    yearsInBusiness: 3,
    homesProtected: "1,000+",
    avgResponseMinutes: 120,
    satisfactionRate: "99.9%",
    googleRating: 4.9,
    reviewCount: 480,
  },
  guarantee: "99.9% Satisfaction & 6-Month Re-treatment Guarantee",
  serviceRadiusKm: 60,
  regionsServed: [
    "Saskatoon",
    "Warman",
    "Martensville",
    "Dalmeny",
    "Osler",
    "Langham",
    "Vanscoy",
    "Corman Park",
    "Dundurn",
    "Clavet",
    "Greenbryre",
    "The Willows",
    "Riverside Estates",
    "Grasswood",
  ],
  serviceLocations: [
    { name: "Toronto (Downtown & East/West)", region: "City of Toronto", badge: "2h Emergency Dispatch" },
    { name: "North York", region: "City of Toronto", badge: "2h Fast Response" },
    { name: "Etobicoke", region: "City of Toronto", badge: "Local Unit on Standby" },
    { name: "Scarborough", region: "City of Toronto", badge: "2h Fast Response" },
    { name: "Mississauga", region: "Peel Region", badge: "2h Emergency Dispatch" },
    { name: "Brampton", region: "Peel Region", badge: "2h Fast Response" },
    { name: "Vaughan", region: "York Region", badge: "Local Unit on Standby" },
    { name: "Markham", region: "York Region", badge: "2h Fast Response" },
    { name: "Oakville", region: "Halton Region", badge: "2h Fast Response" },
    { name: "Richmond Hill", region: "York Region", badge: "Local Unit on Standby" },
    { name: "Burlington", region: "Halton Region", badge: "2h Fast Response" },
  ],
};
