export const COMPANY_DETAILS = {
  name: "K2 Pest Control",
  tagline: "Licensed, Guaranteed & Eco-Conscious Exterminators for Toronto & GTA",
  slogan: "Licensed, Guaranteed & Eco-Conscious Exterminators for Toronto & GTA",
  logoUrl: "/assets/logo.png",
  shortName: "K2 Pest Control",
  phone: "(416) 555-0199",
  phoneRaw: "4165550199",
  email: "info@k2pc.ca",
  licenseNumber: "ON-849201-P",
  provincialBody: "Ontario Ministry of the Environment, Conservation and Parks",
  address: {
    street: "1200 Eglinton Ave E, Suite 400",
    city: "Toronto",
    province: "ON",
    postalCode: "M3C 1H9",
    country: "Canada",
  },
  hours: [
    { days: "Monday - Friday", times: "7:00 AM - 9:00 PM" },
    { days: "Saturday - Sunday", times: "8:00 AM - 6:00 PM" },
    { days: "Emergency Response", times: "24/7 Rapid Dispatch" },
  ],
  stats: {
    yearsInBusiness: 15,
    homesProtected: "12,000+",
    avgResponseMinutes: 120,
    satisfactionRate: "99.4%",
    googleRating: 4.9,
    reviewCount: 480,
  },
  guarantee: "100% Satisfaction & 6-Month Re-treatment Guarantee",
  serviceRadiusKm: 60,
  regionsServed: [
    "Toronto",
    "North York",
    "Etobicoke",
    "Scarborough",
    "Mississauga",
    "Brampton",
    "Vaughan",
    "Markham",
    "Oakville",
    "Richmond Hill",
    "Burlington",
  ],
};
