import { LocationCity } from "@/lib/types";

export const LOCATIONS: LocationCity[] = [
  {
    name: "Toronto (Downtown & East/West)",
    region: "City of Toronto",
    slug: "toronto",
    population: "2.9 Million",
    badge: "2h Emergency Dispatch",
    description:
      "Fast, licensed residential and commercial extermination services across all Toronto neighbourhoods — Downtown Core, East End, West End, and surrounding communities.",
    neighborhoods: [
      "Downtown Core",
      "Annex",
      "Leslieville",
      "Roncesvalles",
      "Beaches",
      "Forest Hill",
    ],
    commonPests: [
      "Mice & Rats (Attic & Foundation Exclusion)",
      "Bed Bugs (Heat & Steam Treatment)",
      "Carpenter Ants & Pavement Ants",
      "Wasps & Hornets",
      "Cockroaches",
    ],
    landmarks: ["CN Tower District", "Kensington Market", "Distillery District"],
    postalCodes: ["M5A", "M5B", "M5C", "M5E", "M5G", "M5H", "M5J", "M5K", "M5L", "M5T", "M5V"],
  },
  {
    name: "North York",
    region: "City of Toronto",
    slug: "north-york",
    population: "660,000+",
    badge: "2h Fast Response",
    description:
      "Rapid pest control and extermination services across North York. Our licensed technicians serve Willowdale, Don Mills, Jane & Finch, Bathurst Manor, and surrounding areas.",
    neighborhoods: ["Willowdale", "Don Mills", "Jane & Finch", "Bathurst Manor", "York Mills"],
    commonPests: [
      "Mice & Rats",
      "Bed Bugs",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Silverfish",
    ],
    landmarks: ["North York Civic Centre", "Mel Lastman Square", "Fairview Mall"],
    postalCodes: ["M2J", "M2M", "M2N", "M2R", "M3A", "M3B", "M3C", "M3H", "M3J", "M3K", "M3L", "M3M", "M3N"],
  },
  {
    name: "Etobicoke",
    region: "City of Toronto",
    slug: "etobicoke",
    population: "360,000+",
    badge: "Local Unit on Standby",
    description:
      "Licensed residential and commercial pest control across Etobicoke. We serve Rexdale, Islington Village, Humber Valley, Mimico, and all surrounding areas.",
    neighborhoods: ["Rexdale", "Islington Village", "Humber Valley", "Mimico", "Long Branch"],
    commonPests: [
      "Mice & Rats",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Bed Bugs",
      "Cockroaches",
    ],
    landmarks: ["Humber College North Campus", "Sherway Gardens", "Centennial Park"],
    postalCodes: ["M8V", "M8W", "M8X", "M8Y", "M8Z", "M9A", "M9B", "M9C", "M9P", "M9R", "M9V", "M9W"],
  },
  {
    name: "Scarborough",
    region: "City of Toronto",
    slug: "scarborough",
    population: "630,000+",
    badge: "2h Fast Response",
    description:
      "Expert pest extermination services across Scarborough and surrounding East Toronto communities including Agincourt, Malvern, Birchcliffe, and Wexford.",
    neighborhoods: ["Agincourt", "Malvern", "Birchcliffe", "Wexford", "Cliffside"],
    commonPests: [
      "Mice & Rats",
      "Bed Bugs",
      "Carpenter Ants",
      "Cockroaches",
      "Wasps & Hornets",
    ],
    landmarks: ["Scarborough Town Centre", "Toronto Zoo", "University of Toronto Scarborough"],
    postalCodes: ["M1B", "M1C", "M1E", "M1G", "M1H", "M1J", "M1K", "M1L", "M1M", "M1N", "M1P", "M1R", "M1S", "M1T", "M1V", "M1W", "M1X"],
  },
  {
    name: "Mississauga",
    region: "Peel Region",
    slug: "mississauga",
    population: "720,000+",
    badge: "2h Emergency Dispatch",
    description:
      "Professional pest control and extermination across Mississauga — Port Credit, Streetsville, Meadowvale, Clarkson, City Centre, and surrounding communities.",
    neighborhoods: ["Port Credit", "Streetsville", "Meadowvale", "Clarkson", "City Centre", "Lakeview"],
    commonPests: [
      "Mice & Rats (Attic & Foundation Exclusion)",
      "Bed Bugs (Heat Treatment)",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Cockroaches",
    ],
    landmarks: ["Square One Shopping Centre", "Port Credit Harbour", "Mississauga Civic Centre"],
    postalCodes: ["L4T", "L4V", "L4W", "L4X", "L4Y", "L4Z", "L5A", "L5B", "L5C", "L5E", "L5G", "L5H", "L5J", "L5K", "L5L", "L5M", "L5N", "L5R", "L5V", "L5W"],
  },
  {
    name: "Brampton",
    region: "Peel Region",
    slug: "brampton",
    population: "650,000+",
    badge: "2h Fast Response",
    description:
      "Licensed pest control across Brampton — Bramalea, Springdale, Heart Lake, Castlemore, Downtown Brampton, and all surrounding residential and commercial areas.",
    neighborhoods: ["Bramalea", "Springdale", "Heart Lake", "Castlemore", "Downtown Brampton"],
    commonPests: [
      "Mice & Rats",
      "Bed Bugs",
      "Carpenter Ants & Pavement Ants",
      "Wasps & Hornets",
      "Cockroaches",
    ],
    landmarks: ["Brampton Civic Hospital", "Gage Park", "Bramalea City Centre"],
    postalCodes: ["L6P", "L6R", "L6S", "L6T", "L6V", "L6W", "L6X", "L6Y", "L6Z", "L7A"],
  },
  {
    name: "Vaughan",
    region: "York Region",
    slug: "vaughan",
    population: "340,000+",
    badge: "Local Unit on Standby",
    description:
      "Rapid extermination and pest prevention services across Vaughan — Woodbridge, Maple, Kleinburg, Concord, and Thornhill communities.",
    neighborhoods: ["Woodbridge", "Maple", "Kleinburg", "Concord", "Thornhill"],
    commonPests: [
      "Mice & Rats",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Bed Bugs",
      "Cluster Flies",
    ],
    landmarks: ["Vaughan Mills", "Canada's Wonderland", "Vaughan Metropolitan Centre"],
    postalCodes: ["L4H", "L4J", "L4K", "L4L", "L6A"],
  },
  {
    name: "Markham",
    region: "York Region",
    slug: "markham",
    population: "360,000+",
    badge: "2h Fast Response",
    description:
      "Professional pest control across Markham — Unionville, Cornell, Milliken Mills, Berczy Village, and surrounding York Region communities.",
    neighborhoods: ["Unionville", "Cornell", "Milliken Mills", "Berczy Village", "Old Markham Village"],
    commonPests: [
      "Mice & Rats",
      "Bed Bugs",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Cockroaches",
    ],
    landmarks: ["Pacific Mall", "Markham Civic Centre", "Toogood Pond"],
    postalCodes: ["L3P", "L3R", "L3S", "L3T", "L6B", "L6C", "L6E", "L6G"],
  },
  {
    name: "Oakville",
    region: "Halton Region",
    slug: "oakville",
    population: "230,000+",
    badge: "2h Fast Response",
    description:
      "Licensed extermination across Oakville — Old Oakville, Glen Abbey, River Oaks, Bronte, and surrounding Halton Region communities.",
    neighborhoods: ["Old Oakville", "Glen Abbey", "River Oaks", "Bronte", "College Park"],
    commonPests: [
      "Mice & Rats",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Bed Bugs",
      "Silverfish & Earwigs",
    ],
    landmarks: ["Oakville Harbour", "Glen Abbey Golf Club", "Sheridan College Trafalgar"],
    postalCodes: ["L6H", "L6J", "L6K", "L6L", "L6M"],
  },
  {
    name: "Richmond Hill",
    region: "York Region",
    slug: "richmond-hill",
    population: "210,000+",
    badge: "Local Unit on Standby",
    description:
      "Pest control and extermination services across Richmond Hill — Oak Ridges, Crosby, Mill Pond, Bayview Hill, and surrounding York Region communities.",
    neighborhoods: ["Oak Ridges", "Crosby", "Mill Pond", "Bayview Hill", "Jefferson"],
    commonPests: [
      "Mice & Rats",
      "Wasps & Hornets",
      "Carpenter Ants",
      "Bed Bugs",
      "Cluster Flies",
    ],
    landmarks: ["Richmond Hill Centre", "Mill Pond Park", "York Region Transit Hub"],
    postalCodes: ["L4B", "L4C", "L4E", "L4S"],
  },
  {
    name: "Burlington",
    region: "Halton Region",
    slug: "burlington",
    population: "200,000+",
    badge: "2h Fast Response",
    description:
      "Professional pest elimination across Burlington — Aldershot, Brant Hills, Orchard, Tyandaga, and surrounding Halton Region communities.",
    neighborhoods: ["Aldershot", "Brant Hills", "Orchard", "Tyandaga", "Downtown Burlington"],
    commonPests: [
      "Mice & Rats",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Bed Bugs",
      "Silverfish",
    ],
    landmarks: ["Burlington Waterfront", "Royal Botanical Gardens", "Joseph Brant Hospital"],
    postalCodes: ["L7L", "L7M", "L7N", "L7P", "L7R", "L7S", "L7T"],
  },
];
