import { LocationCity } from "@/lib/types";

export const LOCATIONS: LocationCity[] = [
  {
    name: "Saskatoon (Central & Suburbs)",
    region: "City of Saskatoon",
    slug: "saskatoon",
    population: "280,000+",
    badge: "Central Dispatch HQ",
    description:
      "Comprehensive, licensed residential and commercial extermination services across all Saskatoon neighbourhoods — Nutana, Stonebridge, Willowgrove, Riversdale, Silverwood Heights, and surrounding areas.",
    neighborhoods: [
      "Nutana",
      "Stonebridge",
      "Willowgrove",
      "Riversdale",
      "Silverwood Heights",
      "City Park",
      "Lakewood",
      "Rosewood",
    ],
    commonPests: [
      "Mice & Voles (Foundation & Garage Exclusion)",
      "Bed Bugs (Heat & Target Treatment)",
      "Carpenter Ants & Pavement Ants",
      "Wasps & Hornets",
      "Cockroaches",
    ],
    landmarks: ["Broadway Avenue", "University of Saskatchewan", "Wanuskewin Heritage Park", "Downtown Saskatoon"],
    postalCodes: ["S7K", "S7L", "S7M", "S7N", "S7P", "S7R", "S7S", "S7T", "S7V", "S7W"],
  },
  {
    name: "Warman",
    region: "Saskatoon Metro Corridor",
    slug: "warman",
    population: "12,500+",
    badge: "~15-20 min dispatch",
    description:
      "Rapid pest control and extermination services across Warman. Our licensed technicians provide fast rodent exclusion, wasp nest removal, and perimeter insect protection.",
    neighborhoods: ["Rockwood", "Traditions", "Prairie Oasis", "Legends"],
    commonPests: [
      "Mice & Rodents",
      "Wasps & Yellowjackets",
      "Ants & Spiders",
      "Grain & Pantry Beetles",
    ],
    landmarks: ["The Legends Centre", "Warman Diamond Rodeo Arena", "Prairie Oasis Park"],
    postalCodes: ["S0K 4S0", "S0K 4S1"],
  },
  {
    name: "Martensville",
    region: "Saskatoon Metro Corridor",
    slug: "martensville",
    population: "10,500+",
    badge: "~15 min dispatch",
    description:
      "Licensed residential and commercial pest control across Martensville. Discrete same-day response for mice, ants, spiders, and wasp removal.",
    neighborhoods: ["Lake Vista", "MacCormack Ranch", "Sunset Ridge"],
    commonPests: [
      "Mice & Rats",
      "Carpenter Ants",
      "Wasps & Hornets",
      "Spiders & Boxelder Bugs",
    ],
    landmarks: ["Martensville Athletic Pavilion", "Kinsmen Park", "Lake Vista"],
    postalCodes: ["S0K 2T0", "S0K 2T1"],
  },
  {
    name: "Dalmeny",
    region: "Saskatoon Metro Corridor",
    slug: "dalmeny",
    population: "2,000+",
    badge: "~25 min dispatch",
    description:
      "Dedicated pest management for Dalmeny homeowners and rural properties. Specialized prairie rodent exclusion and safe insect barriers.",
    neighborhoods: ["Central Dalmeny", "Railway Avenue", "Parkland Estates"],
    commonPests: ["Field Mice & Voles", "Spiders", "Ground Beetles", "Ants"],
    landmarks: ["Dalmeny Community Centre", "Centennial Park"],
    postalCodes: ["S0K 1E0"],
  },
  {
    name: "Osler",
    region: "Saskatoon Metro Corridor",
    slug: "osler",
    population: "1,500+",
    badge: "~20-25 min dispatch",
    description:
      "Fast, reliable pest control for homes, acreages, and agricultural businesses in Osler and surrounding R.M. of Corman Park.",
    neighborhoods: ["Osler Town Centre", "North Estates"],
    commonPests: ["Mice & Rodents", "Cluster Flies", "Wasps", "Ants"],
    landmarks: ["Osler Community Hall", "Osler School Grounds"],
    postalCodes: ["S0K 3A0"],
  },
  {
    name: "Langham",
    region: "Saskatoon Metro Corridor",
    slug: "langham",
    population: "1,500+",
    badge: "~30 min dispatch",
    description:
      "Licensed extermination and pest-proofing for Langham residences, acreages, and workshops along Highway 16.",
    neighborhoods: ["Langham Central", "Park Avenue Properties"],
    commonPests: ["Mice & Voles", "Spiders", "Boxelder Bugs", "Wasps"],
    landmarks: ["Langham Museum", "River Hills Golf Course"],
    postalCodes: ["S0K 2L0"],
  },
  {
    name: "Vanscoy",
    region: "Saskatoon Metro Corridor",
    slug: "vanscoy",
    population: "1,000+",
    badge: "~25 min dispatch",
    description:
      "Targeted pest solutions for Vanscoy, Grandora, and surrounding industrial/residential corridors south-west of Saskatoon.",
    neighborhoods: ["Vanscoy Village", "Grandora Corridors"],
    commonPests: ["Prairie Rodents", "Spiders", "Cockroaches", "Ants"],
    landmarks: ["Vanscoy Community Hall", "Agrium Potash Area"],
    postalCodes: ["S0L 3J0"],
  },
  {
    name: "Corman Park",
    region: "Rural Municipality",
    slug: "corman-park",
    population: "8,500+",
    badge: "~15-30 min dispatch",
    description:
      "Acreage and rural property pest management across R.M. of Corman Park #344. Specialized barn, shop, and outbuilding rodent and spider defense.",
    neighborhoods: ["Grasswood Road", "Pike Lake Corridor", "Beaver Creek"],
    commonPests: ["Field Mice", "Voles", "Spiders", "Wasps", "Cluster Flies"],
    landmarks: ["Corman Park Administrative District", "Beaver Creek Conservation Area"],
    postalCodes: ["S7K", "S7T", "S7V"],
  },
  {
    name: "Dundurn",
    region: "Saskatoon Metro Corridor",
    slug: "dundurn",
    population: "1,200+",
    badge: "~35 min dispatch",
    description:
      "Complete pest extermination for Dundurn, Blackstrap Lake resort properties, and military-adjacent housing.",
    neighborhoods: ["Dundurn Town", "Blackstrap Resort", "Shields Area"],
    commonPests: ["Mice & Rodents", "Spiders", "Ants", "Wasps"],
    landmarks: ["Blackstrap Provincial Park", "Dundurn Community Centre"],
    postalCodes: ["S0K 1K0"],
  },
  {
    name: "Clavet",
    region: "Saskatoon Metro Corridor",
    slug: "clavet",
    population: "1,000+",
    badge: "~25 min dispatch",
    description:
      "Safe, guaranteed pest control for Clavet homes, acreages, and agricultural processing facilities along Highway 16 East.",
    neighborhoods: ["Clavet Central", "Highway 16 East Corridor"],
    commonPests: ["Rodents & Mice", "Grain Beetles", "Ants", "Wasps"],
    landmarks: ["Clavet Composite School", "Bunge Facility Area"],
    postalCodes: ["S0K 0Y0"],
  },
  {
    name: "Greenbryre",
    region: "Saskatoon South Corridor",
    slug: "greenbryre",
    population: "Estates Community",
    badge: "~10-15 min dispatch",
    description:
      "Premium, discrete pest defense for luxury estates in Greenbryre. Comprehensive perimeter barriers and non-invasive foundation sealing.",
    neighborhoods: ["Greenbryre Estates", "Greenbryre Golf Community"],
    commonPests: ["Spiders & Ants", "Mice", "Wasps", "Landscape Beetles"],
    landmarks: ["Greenbryre Golf & Country Club"],
    postalCodes: ["S7V 0A1"],
  },
  {
    name: "The Willows",
    region: "Saskatoon South Corridor",
    slug: "the-willows",
    population: "Residential Community",
    badge: "~10-15 min dispatch",
    description:
      "Quiet, discrete residential pest solutions for The Willows community. Eco-friendly IPM treatments safe for children, pets, and pristine turf.",
    neighborhoods: ["Willows Golf Estates", "Willows Residential"],
    commonPests: ["Ants", "Spiders", "Wasps", "Voles & Mice"],
    landmarks: ["The Willows Club", "Stonebridge South"],
    postalCodes: ["S7T 0G1"],
  },
  {
    name: "Riverside Estates",
    region: "Saskatoon South Corridor",
    slug: "riverside-estates",
    population: "Riverbank Community",
    badge: "~15 min dispatch",
    description:
      "Specialized riverbank pest control for Riverside Estates properties. Moisture insect tracking, spider barrier sprays, and rodent defense.",
    neighborhoods: ["Riverside Drive", "Riverbank Trails"],
    commonPests: ["River Spiders", "Mosquitoes & Midges", "Field Mice", "Ants"],
    landmarks: ["South Saskatchewan River Corridor"],
    postalCodes: ["S7T 0H1"],
  },
  {
    name: "Grasswood",
    region: "Saskatoon South Corridor",
    slug: "grasswood",
    population: "South Corridor",
    badge: "~15 min dispatch",
    description:
      "Fast exterminator dispatch for Grasswood commercial complexes, acreages, and rural residences south of Saskatoon.",
    neighborhoods: ["Grasswood Commercial Strip", "South Country Estates"],
    commonPests: ["Mice & Rats", "Spiders", "Cluster Flies", "Ground Beetles"],
    landmarks: ["Highway 11 South Commercial Hub"],
    postalCodes: ["S7T 1A1"],
  },
  {
    name: "Pike Lake",
    region: "Saskatoon South-West Corridor",
    slug: "pike-lake",
    population: "Resort Community",
    badge: "~25-30 min dispatch",
    description:
      "Cabin, cottage, and acreage pest control for Pike Lake resort communities and Provincial Park area. Seasonal spider barriers, rodent winterization, and ant treatments.",
    neighborhoods: ["Pike Lake Cottage Area", "Parkview Estates", "Highway 766 Corridor"],
    commonPests: ["Spiders", "Carpenter Ants", "Mice & Voles", "Wasps", "Mosquitoes"],
    landmarks: ["Pike Lake Provincial Park", "Pike Lake Recreation Centre"],
    postalCodes: ["S0K 2L0"],
  },
  {
    name: "Whitecap",
    region: "Saskatoon South Corridor",
    slug: "whitecap",
    population: "First Nation & Resort",
    badge: "~25 min dispatch",
    description:
      "Comprehensive residential and commercial pest management for Whitecap Dakota First Nation, resort complexes, and surrounding Highway 219 properties.",
    neighborhoods: ["Whitecap Community", "Dakota Dunes Area"],
    commonPests: ["Ground Beetles", "Field Mice", "Spiders", "Ants", "Wasps"],
    landmarks: ["Dakota Dunes Resort", "Whitecap Health Centre"],
    postalCodes: ["S7K 2L2"],
  },
  {
    name: "Delisle",
    region: "Saskatoon South-West Corridor",
    slug: "delisle",
    population: "1,100+",
    badge: "~30-35 min dispatch",
    description:
      "Licensed pest eradication for Delisle homes, businesses, and surrounding farms along Highway 7 South-West.",
    neighborhoods: ["Delisle Central", "Highway 7 Commercial Strip"],
    commonPests: ["Mice & Rodents", "Cockroaches", "Bed Bugs", "Wasps", "Spiders"],
    landmarks: ["Delisle Curling Rink", "Delisle Composite School"],
    postalCodes: ["S0L 0P0"],
  },
];
