import { Testimonial } from "../types";

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "David K.",
    location: "North York, Toronto",
    rating: 5,
    date: "2 weeks ago",
    serviceReceived: "Rodent Exclusion & Proofing",
    comment: "We heard scratching in our ceiling every night. K2PC arrived within 2 hours of calling, identified 3 mouse access points around our AC pipe lines, sealed them with steel mesh, and set secure traps. No sounds since!",
    verified: true,
  },
  {
    id: "t2",
    name: "Elena M.",
    location: "Mississauga, ON",
    rating: 5,
    date: "1 month ago",
    serviceReceived: "Carpenter Ant Control",
    comment: "Saw carpenter ants near our patio door. Technician Marcus was knowledgeable, polite, and explained how the exterior bait system works. 6-month warranty gave us complete peace of mind. Highly recommend!",
    verified: true,
  },
  {
    id: "t3",
    name: "Robert S.",
    location: "Vaughan, ON",
    rating: 5,
    date: "3 weeks ago",
    serviceReceived: "Wasp Nest Removal",
    comment: "Huge yellowjacket nest right under our rear deck eave. Called at 8:00 AM, technician arrived by 10:30 AM in full gear, removed the nest, and sprayed the overhang. Outstanding speed and safety.",
    verified: true,
  },
  {
    id: "t4",
    name: "Priya & Sunita T.",
    location: "Scarborough, Toronto",
    rating: 5,
    date: "2 months ago",
    serviceReceived: "Bed Bug Thermal Treatment",
    comment: "As apartment renters, we were terrified when we noticed bed bug bites. K2PC treated our 2-bedroom unit discreetly and effectively. Zero bites since. Their team is truly top-tier.",
    verified: true,
  },
  {
    id: "t5",
    name: "Mark B.",
    location: "Brampton, ON",
    rating: 5,
    date: "1 month ago",
    serviceReceived: "Commercial Restaurant IPM Plan",
    comment: "We run a busy Italian bistro. K2PC handles our monthly health audit reporting and pest management. Always audit-ready, punctual, and professional.",
    verified: true,
  },
];
