import { Testimonial } from "../types";

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "David K.",
    location: "Nutana, Saskatoon",
    rating: 5,
    date: "2 weeks ago",
    serviceReceived: "Rodent Exclusion & Proofing",
    comment: "We heard scratching in our ceiling every night. K2 Pest Control arrived quickly, identified 3 mouse access points around our AC pipe lines, sealed them with steel mesh, and set secure traps. No sounds since!",
    verified: true,
  },
  {
    id: "t2",
    name: "Elena M.",
    location: "Warman, SK",
    rating: 5,
    date: "1 month ago",
    serviceReceived: "Carpenter Ant Control",
    comment: "Saw carpenter ants near our patio door. The technician was knowledgeable, polite, and explained how the exterior bait system works. 6-month warranty gave us complete peace of mind. Highly recommend!",
    verified: true,
  },
  {
    id: "t3",
    name: "Robert S.",
    location: "Martensville, SK",
    rating: 5,
    date: "3 weeks ago",
    serviceReceived: "Wasp Nest Removal",
    comment: "Huge yellowjacket nest right under our rear deck eave. Called in the morning, technician arrived promptly in full safety gear, removed the nest, and sprayed the overhang. Outstanding speed and safety.",
    verified: true,
  },
  {
    id: "t4",
    name: "Priya & Sunita T.",
    location: "Stonebridge, Saskatoon",
    rating: 5,
    date: "2 months ago",
    serviceReceived: "Bed Bug Targeted Treatment",
    comment: "We were terrified when we noticed bed bug bites. K2 Pest Control treated our property discreetly and effectively. Zero bites since. Their team is truly top-tier.",
    verified: true,
  },
  {
    id: "t5",
    name: "Mark B.",
    location: "Lakewood, Saskatoon",
    rating: 5,
    date: "1 month ago",
    serviceReceived: "Commercial Facility IPM Plan",
    comment: "We run a busy food service facility in Saskatoon. K2 Pest Control handles our health inspection reporting and pest management. Always audit-ready, punctual, and professional.",
    verified: true,
  },
];
